### PR TITLE
Add standard-libraries-discussion.md

### PR DESCRIPTION
**Pull request by ghost**
Hastily added document that started as an issue [based on my gitter comment](https://gitter.im/scala/slip?at=5618e3b71b0e279854bdb383), but then decided to grow 

@dickwall suggested I added as a PR, just to start some feedback (or not, as the case may be).

### CODE REVIEW

**Comment by Ichoran** [comment]
There's a very important factor regarding C++ that you don't really mention, which is that long-term inclusion of a library in a Linux distribution is a much better indication of the health and stability of a non-standard C++ project than is a jar living on Maven (partly because these things have just been around a lot longer for C++).

Taking lessons from early C++ days is therefore a bit tricky because the world was so different (no internet, no GitHub, no Linux, etc.).

But in any case, using C++ as a comparison _now_ is also tricky because I know that libtiff is a plenty good Tiff library because it's already been curated by virtue of being in my Linux distribution for the past 3+ years, but there is no equivalent readily apparent for Scala (i.e. third parties are doing the work of selecting libs).

**Comment by non** [comment]
One other interesting difference is that some of these projects (e.g. Perl with CPAN) have a canonical package namespace. What this means is that there is a central source of truth regarding what `Test::Simple` means, who maintains it, what versions are available, etc. In Perl, this means that

**Comment by non** [comment]
So while attempting to write a comment I closed this issue. Sorry! I just reopened it.

**Comment by ghost** [comment]
The  document Is far from finished.... The Focus on c++ was just the start. Perhaps your comments are best added to the document as they are interresting to get peoples opinion, regardless of whether others agree?

**Comment by dickwall** [comment]
Was issue #25 closed deliberately @InTheNow ?

**Comment by SethTisue** [comment]
Closing since the SLIP process is being replaced by the new Scala Platform Process (http://www.scala-lang.org/blog/2016/11/28/spp.html).

This could be a good discussion to start/restart at http://contributors.scala-lang.org

**Pull request closed without merging**
